"""
Database models and connection management for Drugstore Canary
"""
from datetime import datetime
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, ForeignKey, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from config import DATABASE_URL, BASE_DIR

Base = declarative_base()

class Zone(Base):
    """Geographic zones in Hat Yai"""
    __tablename__ = "zones"
    
    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    center_lat = Column(Float)
    center_lon = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    pharmacies = relationship("Pharmacy", back_populates="zone")
    alerts = relationship("Alert", back_populates="zone")


class Pharmacy(Base):
    """Pharmacy/drugstore locations"""
    __tablename__ = "pharmacies"
    
    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    zone_id = Column(String, ForeignKey("zones.id"))
    latitude = Column(Float)
    longitude = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    zone = relationship("Zone", back_populates="pharmacies")
    sales = relationship("PharmacySales", back_populates="pharmacy")


class MedicineType(Base):
    """Medicine categories and types"""
    __tablename__ = "medicine_types"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    category = Column(String, nullable=False)  # fever, diarrhea, skin_infection, etc.
    name = Column(String, nullable=False)
    description = Column(String)
    
    sales = relationship("PharmacySales", back_populates="medicine")


class PharmacySales(Base):
    """Daily sales data for each pharmacy and medicine type"""
    __tablename__ = "pharmacy_sales"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    pharmacy_id = Column(String, ForeignKey("pharmacies.id"), nullable=False)
    medicine_id = Column(Integer, ForeignKey("medicine_types.id"), nullable=False)
    date = Column(DateTime, nullable=False)
    quantity_sold = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    pharmacy = relationship("Pharmacy", back_populates="sales")
    medicine = relationship("MedicineType", back_populates="sales")


class FloodData(Base):
    """Flood event data for correlation analysis"""
    __tablename__ = "flood_data"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    zone_id = Column(String, ForeignKey("zones.id"))
    date = Column(DateTime, nullable=False)
    water_level_cm = Column(Float)
    duration_hours = Column(Float)
    severity = Column(String)  # low, medium, high
    created_at = Column(DateTime, default=datetime.utcnow)


class Alert(Base):
    """Anomaly alerts generated by the system"""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    zone_id = Column(String, ForeignKey("zones.id"), nullable=False)
    medicine_category = Column(String, nullable=False)
    alert_level = Column(String, nullable=False)  # low, medium, high, critical
    anomaly_score = Column(Float, nullable=False)
    confidence = Column(Float)
    detected_at = Column(DateTime, default=datetime.utcnow)
    message = Column(String)
    is_active = Column(Boolean, default=True)
    resolved_at = Column(DateTime)
    
    zone = relationship("Zone", back_populates="alerts")


class ModelPrediction(Base):
    """Store model predictions for analysis"""
    __tablename__ = "model_predictions"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    zone_id = Column(String, ForeignKey("zones.id"))
    medicine_category = Column(String, nullable=False)
    date = Column(DateTime, nullable=False)
    model_type = Column(String, nullable=False)  # prophet, lstm, ensemble
    predicted_value = Column(Float)
    actual_value = Column(Float)
    anomaly_score = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)


# Database initialization
def init_db():
    """Initialize database and create all tables"""
    # Ensure data directory exists
    data_dir = BASE_DIR / "data"
    data_dir.mkdir(exist_ok=True)
    
    engine = create_engine(DATABASE_URL, echo=False)
    Base.metadata.create_all(engine)
    return engine


def get_session():
    """Get database session"""
    engine = create_engine(DATABASE_URL, echo=False)
    Session = sessionmaker(bind=engine)
    return Session()


if __name__ == "__main__":
    print("Initializing database...")
    engine = init_db()
    print(f"Database initialized successfully at: {DATABASE_URL}")
    print(f"Tables created: {', '.join(Base.metadata.tables.keys())}")
